version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:14.15.5 # Reverted to the previous Node.js version
    steps:
      - checkout
      - run:
          name: Deploy App
          command: |
            npm install
            npm run api:deploy && npm run frontend:deploy

workflows:
  version: 2
  deploy:
    jobs:
      - deploy